stages:
- test
- deploy

.setup: &setup_definition
  image: ideascube/ideascube-ci:jessie-python34
  before_script:
  - pew in venv make sync-deps

.test: &test_definition
  <<: *setup_definition
  script:
  - pew in venv make test


Code Quality:
  <<: *setup_definition
  script:
  - pew in venv make quality-check


Master Debian Package:
  stage: deploy
  image: ideascube/ideascube-ci:jessie-deb-builder
  script:
  - dpkg-buildpackage -us -uc
  - pwd
  - ls -la
  artifacts:
    name: "ideascube-debian-${CI_COMMIT_REF_NAME}"
    expire_in: "1 month"
    paths:
    - ideascube_*.deb
#  only:
#  - master
