.setup: &setup_definition
  image: ideascube/ideascube-ci:jessie-python34
  before_script:
  - pew in venv make develop

.test: &test_definition
  <<: *setup_definition
  script:
  - pew in venv make test


Data Migration:
  <<: *setup_definition
  script:
  - pew in venv make test-data-migration
