stages:
- test
- deploy

.setup: &setup_definition
  image: ideascube/ideascube-ci:jessie-python34
  before_script:
  - pew in venv make sync-deps

.test: &test_definition
  <<: *setup_definition
  script:
  - pew in venv make test


"Tests: Jessie/Python-3.4":
  <<: *test_definition

"Tests: Stretch/Python-3.5":
  <<: *test_definition
  image: ideascube/ideascube-ci:stretch-python35

"Tests: C locale":
  <<: *setup_definition
  script:
  - LC_ALL=C pew in venv make test


Code Coverage:
  <<: *setup_definition
  script:
  - pew in venv make test-coverage


Code Quality:
  <<: *setup_definition
  script:
  - pew in venv make quality-check


Data Migration:
  <<: *setup_definition
  script:
  - pew in venv make test-data-migration

Missing Migrations:
  <<: *setup_definition
  script:
  - pew in venv make check-missing-migrations


Master Debian Package:
  stage: deploy
  image: ideascube/ideascube-ci:jessie-deb-builder
  script:
  - dpkg-buildpackage -us -uc
  artifacts:
    paths:
    - *.deb
#  only:
#  - master
