.setup: &setup_definition
  image: ideascube/ideascube-ci:jessie-python34-test
  before_script:
  - pew in venv make sync-deps

.test: &test_definition
  <<: *setup_definition
  script:
  - pew in venv make test


"Tests: Jessie/Python-3.4":
  <<: *test_definition

"Tests: Stretch/Python-3.5":
  <<: *test_definition
  image: ideascube/ideascube-ci:stretch-python35

"Tests: C locale":
  <<: *test_definition
  variables:
    LC_ALL: "C"


Code Coverage:
  <<: *setup_definition
  script:
  - pew in venv make test-coverage


Code Quality:
  <<: *setup_definition
  script:
  - pew in venv make quality-check


Data Migration:
  <<: *setup_definition
  script:
  - pew in venv make test-data-migration

Missing Migrations:
  <<: *setup_definition
  script:
  - pew in venv make check-missing-migrations
