stages:
- test
- deploy

.setup: &setup_definition
  image: ideascube/ideascube-ci:jessie-python34
  before_script:
  - pew in venv make sync-deps

.test: &test_definition
  <<: *setup_definition
  script:
  - pew in venv make test


Code Quality:
  <<: *setup_definition
  script:
  - pew in venv make quality-check


Master Debian Package:
  stage: deploy
  image: ideascube/ideascube-ci:jessie-deb-builder
  script:
  - sed -i '1 s|^ideascube [(]\(.*\)[)] \(.*\)$|ideascube (\1+${CI_COMMIT_SHA}) \2|' debian/changelog | head -1
  - dpkg-buildpackage -us -uc
  - mv ../ideascube_*.deb .
  artifacts:
    name: "ideascube-debian-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}"
    expire_in: "1 month"
    paths:
    - ideascube_*.deb
#  only:
#  - master
